### ISSUE TITLE
Herramientas a utilizar. 

### ISSUE THREAD

**Issue by Angatupyry** [Angatupyry/is2#1]
Analizar qué herramientas se usarán para el desarrollo del software. 
Dar ideas para el backend y el frontend. 
Se resolvió utilizar base de datos relacional pero aún no cuál de ellas.

**Comment by Angatupyry** [comment]
- Backend: NodeJs, Express. Python - Django

- Frontend: Angular - React - Vue.

- BD: Postgres

**Comment by R-A-G-V** [comment]
Backend: A mi parecer la mejor opción y que me seduce implementar es la de NodeJs por estar enfocado en la web(no es exclusivo) https://www.youtube.com/watch?v=4KvRFJ73vds usando el framework Exprees ya que van de la mano siendo el mas popular https://www.youtube.com/watch?v=SgBQPd6O1hM

Frontend: Menor curva de aprendizaje Vue pero no es completo, confuso Reac y Angular completo y grande https://www.youtube.com/watch?v=IxG7UuFCxKI

BD: Postgres por ser de competencia a nivel mundial ademas de ser de codigo abierto https://www.youtube.com/watch?v=cdIJZZmY9jw

**Comment by Angatupyry** [comment]
Concuerdo en que Vue tiene mejor curva de aprendizaje en cuanto a tiempo. ¿A qué referís con "no es completo"?
NodeJs es fantástico. No sé cuánto es su curva de aprendizaje. A mí me pareció bastante sencillo y práctico. 
Python - Django es fácil y no lo quiero descartar porque todos manejamos python de alguna manera.

**Comment by Arias7** [comment]
Backend: a mi me parecería mejor usar Python ya que es un lenguaje que creo todos manejamos por lo menos un poco.
Frontend: para mi seria mejor vue

y para la base de datos Postgres

**Comment by acem0301** [comment]
Django vs Node.js

https://qgoi8lseuwlwvmgkgjciva-on.drv.tw/website/
https://dzone.com/articles/nodejs-vs-djangois-javascript-better-than-python

He estado leyendo y recomiendan más Node.js para para proyectos pequeños como el nuestro debido a su facilidad de aprendizaje y flexibilidad. Además podremos usar un solo lenguaje base para Frontend y Backend que sería Javascript.

**Comment by R-A-G-V** [comment]
**Obs** "no es completo" solo me refería al nivel de  robustez, nada mas. 
Backend: Si es por aprender algo nuevo Nodjs(en mi caso) pero si es por no perder mucho tiempo Python ya que en algun momento todos lo vimos.
Frontend: Vue
Bd: Postgres

**Comment by Angatupyry** [comment]
Herramientas a utilizar;
NodeJS - Express - Sequelize - Vue - Postgres.
