### ISSUE TITLE
Investigar sobre Callbacks.

### ISSUE THREAD

**Issue by Angatupyry** [Angatupyry/is2#2]
Leer los async-await de NodeJS.
¿Qué son los callbacks?, ¿qué son las funciones síncronas y asíncronas?

**Comment by R-A-G-V** [comment]
-Los callbacks es solo el nombre que se usa para referirse a ciertas funciones,  en lugar de devolver inmediatamente un resultado como la mayoría de las funciones, las funciones que utilizan callbacks toman un tiempo para producir un resultado. La palabra “asíncrono” significa que “requiere algo de tiempo” o “sucede en el futuro, no en este momento”.
-Async(funciones), la idea es reemplazar callback por async-await
