### ISSUE TITLE
Investigación Git

### ISSUE THREAD

**Issue by Angatupyry** [Angatupyry/is2#4]
Conocer los comandos básicos de git e investigar qué herramienta gráfica les parece más cómodo para utilizar.

**Comment by R-A-G-V** [comment]
Comandos básicos de git (conocer) https://www.hostinger.es/tutoriales/comandos-de-git
¿A que te referís con herramienta gráfica?

**Comment by Angatupyry** [comment]
Respuesta dada en persona.
