### ISSUE TITLE
Entorno de desarrollo. 

### ISSUE THREAD

**Issue by Angatupyry** [Angatupyry/is2#5]
Instalar las siguientes herramientas;
Un editor de código. Yo recomiendo VSCode. 
Node https://nodejs.org/en/
Git https://git-scm.com/
Postgres https://www.postgresql.org/
Recomiendo además una distribución de Linux por la comodidad en la terminal pero si se usa Windows no hay ningún problema.

**Comment by R-A-G-V** [comment]
Perfecto.
Me quedo en windows por el momento.
