### ISSUE TITLE
Crear script de la base de datos. 

### ISSUE THREAD

**Issue by Angatupyry** [Angatupyry/is2#9]

**Comment by Angatupyry** [comment]
[DER Inge2.pdf](https://github.com/Angatupyry/is2/files/4283258/DER.Inge2.pdf)

**Comment by R-A-G-V** [comment]
[DER Inge2.pdf](https://github.com/Angatupyry/is2/files/4304089/DER.Inge2.pdf)

**Comment by R-A-G-V** [comment]
[DER Inge2.pdf](https://github.com/Angatupyry/is2/files/4304091/DER.Inge2.pdf)

**Comment by R-A-G-V** [comment]
[SCRIPTIS2.txt](https://github.com/Angatupyry/is2/files/4304092/SCRIPTIS2.txt)

**Comment by Angatupyry** [comment]
[scriptActualizado.txt](https://github.com/Angatupyry/is2/files/4333260/scriptActualizado.txt)

**Comment by acem0301** [comment]
Última versión del script: 
[scriptActualizado.txt](https://github.com/Angatupyry/is2/files/4362090/scriptActualizado.txt)
